image:
  file: .gitpod.Dockerfile

tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      mkdir -p $HOME/.config/httpie
      cp assets/config.json $HOME/.config/httpie
      pip3 install httpie-astra==0.1.3
      cd /home/gitpod/stargate/docker-compose/cassandra-4.0; docker compose up -d
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/hemidactylus/katapod/releases/download/1.1.0-beta2/katapod-1.1.0-beta2.vsix
