image:
  file: .gitpod.Dockerfile

tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      mkdir -p $HOME/.config/httpie
      pip3 install httpie-astra==0.1.3
      sudo /home/gitpod/.astra/cli/astra setup -t "AstraCS:bdBaXXGBfDHUCcEGeBzQfumZ:1ca0ae356009dd8dcd36d9c0b210968731741cb3d727c4553ab1840c61ee2d08"
      sudo /home/gitpod/.astra/cli/astra db create-dotenv stargate -k swag -d $HOME/.config
      sudo /home/gitpod/.pyenv/shims/python assets/set-environment.py $HOME/.config/.env swag
      sudo rm -rf /workspace/httpie-katapod/.newenv
      sudo mv /home/gitpod/.astrarc /root
      cp /workspace/httpie-katapod/assets/config-astra.json $HOME/.config/httpie/config.json
github:
  prebuilds:
    main: true
vscode:
  extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
ports:
  - name: stargate
    port: 8000-10000
    onOpen: ignore
