image:
  file: .gitpod.Dockerfile

tasks:
  - name: install-dependencies
    before: |
      printf 'export PATH="$HOME%s:$PATH"\n' "/.astra/cli" >> $HOME/.bashrc
      printf 'unset JAVA_TOOL_OPTIONS\n' >> $HOME/.bashrc
      curl -Ls "https://dtsx.io/get-astra-cli" | bash >> ./install.log
      mkdir -p $HOME/.config/httpie
      cp assets/config.json $HOME/.config/httpie
      pip3 install httpie-astra==0.1.3
github:
  prebuilds:
    main: true
vscode:
   extensions:
    - https://github.com/DataStax-Academy/katapod/releases/download/stable/katapod-stable.vsix
ports:
  - name: stargate
    port: 8000-10000
    onOpen: ignore
